//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothingStoreNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSuppliers
    {
        public int ProductId { get; set; }
        public int SupplierId { get; set; }
        public int Id { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
